(ns retro.client-headers)

(def greet 0)
(def fuse-rights 2)
(def user-details 5)
(def credits 6)
(def club 7)
(def pub-key 8)
(def room-directory 19)
(def ban 35)
(def room-info 54)
(def navigate 220)
(def user-flat-cats 221)
