(ns retro.client-headers)

(def greet 0)
(def fuse-rights 2)
(def user-details 5)
(def credits 6)
(def club 7)
(def pub-key 8)
(def room-directory 19)
(def users 28)
(def wall-items 30)
(def heightmap 31)
(def floor-items 32)
(def movement 34)
(def ban 35)
(def try-flat 41)
(def items 45)
(def room-decoration 46)
(def room-info 54)
(def goto-flat 59)
(def room-model 69)
(def ad 166)
(def navigate 220)
(def user-flat-cats 221)
(def get-interest 258)
